### ISSUE TITLE
loggy_rsyslog_ng_tls error using default configuration

### ISSUE THREAD

**Issue by ajsharp** [jakshi/loggly_rsyslog_ng#1] opened 2015-06-05 23:18 UTC
I got the following error trying to use the `loggly_rsyslog_ng` LWRP. Does the provider class need to be manually required?

```
NameError
---------
No resource, method, or local variable named `loggy_rsyslog_ng_tls' for `Chef::Provider::LogglyRsyslogNg ""'

 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/loggly_rsyslog_ng/providers/default.rb:38:in `block in class_from_file'
```

**Comment by jakshi** [comment] 2015-06-09 08:21
Hello Alex,

Could you please you show me part of the code you use for calling this LWRP (except for sensitive data of course)?

I want to reproduce the error, so I can fix it.

I think it happens because I called loggly_rsyslog_ng_tls provider without arguments inside loggly_rsyslog_ng provider :-|

**Comment by jakshi** [comment] 2015-06-09 08:35
Just for now try to use cookbook like:

```
loggly_rsyslog_ng_tls 'rsyslog.loggly.crt'

loggly_rsyslog_ng '/etc/rsyslog.d/22-loggly.conf' do
  install_tls_certs false
  loggly_token      'my_very_secure_token'
  log_files         [{
      :filename => '/var/log/syslog',
      :statefile => 'syslog',
      :facility => 'local6'
                    }]
  tags              [ node.chef_environment ]
end
```

**Comment by ajsharp** [comment] 2015-06-09 18:01
This is the full code of the recipe I've written to use it:

```
shared_path = "/srv/www/APP/shared/log"
env = node[:deploy][:APP][:rails_env]

loggly_rsyslog_ng '/etc/rsyslog.d/21-rails.conf' do
  loggly_token node[:loggly][:token]
  tags [env, 'APP']
  log_files([
    {filename: "#{shared_path}/#{env}.log", tag: "rails"},
    {filename: "#{shared_path}/unicorn.stderr.log", tag: "unicorn"},
    {filename: "#{shared_path}/unicorn.stdout.log", tag: "unicorn"}
  ])
end

loggly_rsyslog_ng '/etc/rsyslog.d/21-sidekiq.conf' do
  loggly_token node[:loggly][:token]
  tags [env, 'APP']
  log_files([
    {filename: "#{shared_path}/sidekiq.log", tag: "sidekiq"}
  ])
end

loggly_rsyslog_ng '/etc/rsyslog.d/21-nginx.conf' do
  loggly_token node[:loggly][:token]
  tags [env, 'APP']
  log_dirs([
    {directory: "/var/log/nginx", tag: "nginx"}
  ])
end
```

And this is the full error stacktrace from chef:

```
NameError
---------
No resource, method, or local variable named `loggy_rsyslog_ng_tls' for `Chef::Provider::LogglyRsyslogNg ""'
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/loggly_rsyslog_ng/providers/default.rb:38:in `block in class_from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/buzzstarter/recipes/logging.rb
 
4: loggly_rsyslog_ng '/etc/rsyslog.d/21-rails.conf' do
5:   loggly_token node[:loggly][:token]
6:   tags [env, 'APP']
7:   log_files([
8:     {filename: "#{shared_path}/#{env}.log", tag: "rails"},
9:     {filename: "#{shared_path}/unicorn.stderr.log", tag: "unicorn"},
10:     {filename: "#{shared_path}/unicorn.stdout.log", tag: "unicorn"}
11:   ])
12: end
13: 
```

**Comment by ajsharp** [comment] 2015-07-15 06:03
@jakshi ping

**Comment by jakshi** [comment] 2015-07-15 08:15
Hello Alex,

Do you have the same error with last version of cookbook?

Kindest Regards.
Konstantin.

**Comment by ajsharp** [comment] 2015-07-16 02:55
Yep, same error. 

- Alex Sharp

**Comment by noahsw** [comment] 2015-07-22 06:20
Same issue here:

```
# project/config/chef/site-cookbooks/my-project/recipes/loggly.rb

include_recipe "loggly_rsyslog_ng"

loggly_rsyslog_ng '/etc/rsyslog.d/22-loggly.conf' do
  loggly_token      '##removed##'
  tags              [ node.chef_environment ]
end
```

When provisioning I get this error:
```
==> staging: [2015-07-21T23:18:06-07:00] ERROR: No resource or method named `loggly_rsyslog_ng' for `Chef::Recipe "loggly"'
```

```
# Abbreviated Cheffile.lock

    loggly_rsyslog_ng (4.2.0)
      apt (~> 2.0)
      rsyslog (~> 1.13.0)
```

**Comment by ajsharp** [comment] 2015-07-22 17:09
Yea, the default recipe is broken, I think because it defers to the SSL version, which doesn't require the default file. I think requiring the file will fix it. 

- Alex Sharp

**Comment by jakshi** [comment] 2015-07-26 14:53
Hello @ajsharp 

I added simple test setup for the cookbook, Reproduce the error and fixed it.
Please try new cookbook version.

**Comment by jakshi** [comment] 2015-08-06 03:46
Hello @ajsharp 

As I saw no error in my tests and there're no error reports from you I suppose that it's fixed.
I'm closing the issue.

Kindest Regards.
Konstantin.

**Closed by jakshi** 2015-08-06 03:46 UTC
